#!/bin/bash

export HF_HOME=/path/to/your/hf_cache
export TRANSFORMERS_CACHE=$HF_HOME/hub
export HF_HUB_CACHE=$HF_HOME/hub
export HF_DATASETS_CACHE=$HF_HOME/datasets
export HF_MODULES_CACHE=$HF_HOME/modules
export HF_TOKEN=your_huggingface_token_here
